Pre process

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("traffic_stops - traffic_stops_with_vehicle_number.csv")

C:\Users\ruban\AppData\Local\Temp\ipykernel_908\211946039.py:1: DtypeWarning: Columns (0: search_type) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("traffic_stops - traffic_stops_with_vehicle_number.csv")

In [3]:
print(df)

        stop_date stop_time country_name driver_gender  driver_age_raw  \
0      2020-01-01   0:00:00       Canada             M              59
1      2020-01-01   0:01:00        India             M              35
2      2020-01-01   0:02:00          USA             M              26
3      2020-01-01   0:03:00       Canada             M              26
4      2020-01-01   0:04:00       Canada             M              62
...           ...       ...          ...           ...             ...
65533  2020-02-15  12:13:00        India             F              54
65534  2020-02-15  12:14:00       Canada             F              18
65535  2020-02-15  12:15:00          USA             M              27
65536  2020-02-15  12:16:00       Canada             F              49
65537  2020-02-15  12:17:00          USA             F              72

       driver_age driver_race     violation_raw violation  search_conducted  \
0              19       Asian     Drunk Driving  Speeding              True
1              58       Other             Other     Other             False
2              76       Black  Signal Violation  Speeding             False
3              76       Black          Speeding       DUI              True
4              75       Other          Speeding     Other             False
...           ...         ...               ...       ...               ...
65533          48       Black             Other     Other             False
65534          35    Hispanic          Seatbelt     Other              True
65535          41       Asian          Seatbelt       DUI              True
65536          63       Black          Seatbelt     Other             False
65537          32       Other          Seatbelt  Speeding              True

          search_type stop_outcome  is_arrested stop_duration  \
0      Vehicle Search       Ticket         True     16-30 Min
1      Vehicle Search       Arrest         True     16-30 Min
2               Frisk       Ticket         True     16-30 Min
3               Frisk      Warning        False      0-15 Min
4      Vehicle Search       Arrest         True     16-30 Min
...               ...          ...          ...           ...
65533  Vehicle Search       Arrest         True     16-30 Min
65534  Vehicle Search       Ticket        False     16-30 Min
65535           Frisk       Ticket         True       30+ Min
65536             NaN      Warning         True      0-15 Min
65537             NaN       Ticket         True     16-30 Min

       drugs_related_stop vehicle_number
0                    True     UP76DY3473
1                    True     RJ83PZ4441
2                    True     RJ32OM7264
3                    True     RJ76TI3807
4                   False     WB63BB8305
...                   ...            ...
65533               False     DL56GW6568
65534                True     TN73EO7098
65535                True     GJ33MX8328
65536                True     KA24UZ8488
65537               False     UP89PT2924

[65538 rows x 16 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  str
 1   stop_time           65538 non-null  str
 2   country_name        65538 non-null  str
 3   driver_gender       65538 non-null  str
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  str
 7   violation_raw       65538 non-null  str
 8   violation           65538 non-null  str
 9   search_conducted    65538 non-null  bool
 10  search_type         43818 non-null  str
 11  stop_outcome        65538 non-null  str
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  str
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  str
dtypes: bool(3), int64(2), str(11)
memory usage: 11.4 MB

In [5]:
df["search_type"] = df["search_type"].fillna("Unknown")
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,Unknown,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,Unknown,Ticket,True,16-30 Min,False,UP89PT2924

In [6]:
df["is_arrested"] = df["is_arrested"].astype(int)
df["search_conducted"] = df["search_conducted"].astype(int)
df["drugs_related_stop"] = df["drugs_related_stop"].astype(int)

In [7]:
df["stop_date"] = pd.to_datetime(df["stop_date"], errors='coerce')
df["stop_date"] = df["stop_date"].dt.strftime('%Y-%m-%d')

In [8]:
df.to_csv('cleaned_traffic_stops', index=False)

In [9]:
from sqlalchemy import create_engine

# Create SQLite DB in memory (or use 'sqlite:///traffic.db' for file)
engine = create_engine('sqlite:///traffic_stops.db')

In [10]:
# Load the cleaned dataset
df = pd.read_csv('cleaned_traffic_stops')
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,1,Vehicle Search,Ticket,1,16-30 Min,1,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,0,Vehicle Search,Arrest,1,16-30 Min,1,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,0,Frisk,Ticket,1,16-30 Min,1,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,1,Frisk,Warning,0,0-15 Min,1,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,0,Vehicle Search,Arrest,1,16-30 Min,0,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,0,Vehicle Search,Arrest,1,16-30 Min,0,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,1,Vehicle Search,Ticket,0,16-30 Min,1,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,1,Frisk,Ticket,1,30+ Min,1,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,0,Unknown,Warning,1,0-15 Min,1,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,1,Unknown,Ticket,1,16-30 Min,0,UP89PT2924

In [ ]:
from sqlalchemy import create_engine

username = 'root'
password = '1909'
host = '127.0.0.1'        
port = '3306'             
database = 'traffic_logs'

engine = create_engine(f'mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}')